server:
  port: ${IEXEC_SMS_PORT:15443}
  http:
    enabled: ${IEXEC_SMS_HTTP_ENABLED:true}
    port: ${IEXEC_SMS_HTTP_PORT:15000}
  ssl:
    key-store: ${IEXEC_SMS_SSL_KEYSTORE:./src/main/resources/ssl-keystore-dev.p12} #iexec-core dev certificate for dev
    key-store-password: ${IEXEC_SMS_SSL_KEYSTORE_PASSWORD:whatever}
    key-store-type: ${IEXEC_SMS_SSL_KEYSTORE_TYPE:PKCS12}
    key-alias: ${IEXEC_SMS_SSL_KEYSTORE_ALIAS:iexec-core}
    client-auth: need

# Not sure it's a good idea but here is a link for an embedded mongodb
# https://www.baeldung.com/spring-boot-embedded-mongodb
spring:
  data:
    mongodb:
      database: iexec-sms
      host: ${IEXEC_SMS_MONGO_HOST:localhost}
      port: ${IEXEC_SMS_MONGO_PORT:37017}

blockchain:
  id: ${IEXEC_CHAIN_ID:17}
  nodeAddress: ${IEXEC_SMS_BLOCKCHAIN_NODE_ADDRESS:http://localhost:8545}
  hubAddress: ${IEXEC_HUB_ADDRESS:0x60E25C038D70A15364DAc11A042DB1dD7A2cccBC}
  gasPriceMultiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.0} # txs will be send with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
  gasPriceCap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap
  isSidechain: ${IEXEC_IS_SIDECHAIN:false}

scone:
  cas:
    host: ${IEXEC_SCONE_CAS_HOST:localhost}
    port: ${IEXEC_SCONE_CAS_PORT:8081}
    palaemon:
      configFile:
        withDataset: ${IEXEC_PALAEMON_CONFIG_FILE_WITH_DATASET:./src/main/resources/palaemonConfTemplateWithDataset.vm}
        withoutDataset: ${IEXEC_PALAEMON_CONFIG_FILE_WITHOUT_DATASET:./src/main/resources/palaemonConfTemplateWithoutDataset.vm}
  mrenclave: # TODO: Read that from requester params
    encrypter: # nexus.iex.ec/tee-encrypter-only:1.0.0
      "86d8f0a922a5602c2455bb402c15d559f6c4d488076878d8e681411b2c2224ad|74b6611ac1be12b0f4cd57e5dea69a70|4e6758e38f332d8eb718bc0037dbdedd00d3bb196dd3ff894938b32156179c38"
    #encrypter: # nexus.iex.ec/tee-signer:1.0.0
      #"d7453a4dec5682e9e617c9839f7ff29a10900ef36bc4a9e0c836fa438978c63c|967983ec9d5fe20d2a4ecb74fd4121ee|4e6758e38f332d8eb718bc0037dbdedd00d3bb196dd3ff894938b32156179c38"
    uploader:
      dropbox: # nexus.iex.ec/tee-post-compute:1.0.0
        "7d2142b01982b75e0fde349e39d8524072ae9e6bfa578e90bc60e8a17c8a0581|c546c04052c83271fd9c1e12961b53d6|a5681b7b4c77f284880c95f194c8db17929512cacae021e23cd698fe1100784e"
      #dropbox: # nexus.iex.ec/tee-dropbox-uploader:1.0.0
        #"927e5555a8eb204ec0d5aa70f9f3bd55ef575ff68eb6edf82364c2ae14f83256|2a3fce429fedb8a222548e8ba673303b|a5681b7b4c77f284880c95f194c8db17929512cacae021e23cd698fe1100784e"