server:
  port: ${IEXEC_SMS_PORT:13300}

# Not sure it's a good idea but here is a link for an embedded mongodb
# https://www.baeldung.com/spring-boot-embedded-mongodb
#spring:
#  data:
#    mongodb:
#      database: iexec-sms
#      host: ${IEXEC_SMS_MONGO_HOST:localhost}
#      port: ${IEXEC_SMS_MONGO_PORT:37017}
      #ssl-enabled: true

# Embedded H2 inside JVM
spring:
  profiles:
    active: ${IEXEC_SMS_TEE_RUNTIME_FRAMEWORK:} # gramine/scone
  datasource:
    url: ${IEXEC_SMS_H2_URL:jdbc:h2:file:/data/sms-h2} # will get or create /data/sms-h2.mv.db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: ${IEXEC_SMS_H2_CONSOLE:false} # http://localhost:13300/h2-console/
      settings.web-allow-others: ${IEXEC_SMS_H2_CONSOLE:false} # Get console if Docker run

encryption:
  # Will get previous key or else create one on this path
  # this file shouldn't be clearly readable outside the enclave (but encrypted content could be copied outside)
  aesKeyPath: ${IEXEC_SMS_STORAGE_ENCRYPTION_AES_KEY_PATH:/backup/iexec-sms-aes.key}

blockchain:
  id: ${IEXEC_CHAIN_ID:134}
  is-sidechain: ${IEXEC_IS_SIDECHAIN:true}
  node-address: ${IEXEC_SMS_BLOCKCHAIN_NODE_ADDRESS:https://bellecour.iex.ec}
  hub-address: ${IEXEC_HUB_ADDRESS:0x3eca1B216A7DF1C7689aEb259fFB83ADFB894E7f}
  block-time: ${IEXEC_BLOCK_TIME:PT5S}
  gas-price-multiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.0} # txs will be sent with networkGasPrice*gasPriceMultiplier, 4.0 means superfast
  gas-price-cap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap

metrics:
  storage:
    refresh-interval: ${IEXEC_SMS_METRICS_STORAGE_REFRESH_INTERVAL:30}  # In seconds

logging:
  tee.display-debug-session: ${IEXEC_SMS_DISPLAY_DEBUG_SESSION:false}
#  level:
#    org.springframework: DEBUG
#    org.apache.http: DEBUG

springdoc:
  packagesToScan: com.iexec.sms
  pathsToMatch: /**
