tee:
  secret-provisioner:
    web:
      hostname: ${IEXEC_SECRET_PROVISIONER_WEB_HOSTNAME:localhost}
      port: ${IEXEC_SECRET_PROVISIONER_WEB_PORT:8080}
    enclave:
      hostname: ${IEXEC_SECRET_PROVISIONER_ENCLAVE_HOSTNAME:localhost}
      port: ${IEXEC_SECRET_PROVISIONER_ENCLAVE_PORT:4433}

  worker:
    pre-compute:
      image: ${IEXEC_TEE_WORKER_PRE_COMPUTE_IMAGE:} # e.g.: docker.io/iexechub/tee-worker-pre-compute:x.y.z-production
      fingerprint: ${IEXEC_TEE_WORKER_PRE_COMPUTE_FINGERPRINT:}
      heap-size-gb: ${IEXEC_TEE_WORKER_PRE_COMPUTE_HEAP_SIZE_GB:3}
      entrypoint: ${IEXEC_TEE_WORKER_PRE_COMPUTE_ENTRYPOINT:/bin/bash /apploader.sh}
    post-compute:
      image: ${IEXEC_TEE_WORKER_POST_COMPUTE_IMAGE:} # e.g.: docker.io/iexechub/tee-worker-post-compute:x.y.z-production
      fingerprint: ${IEXEC_TEE_WORKER_POST_COMPUTE_FINGERPRINT:}
      heap-size-gb: ${IEXEC_TEE_WORKER_POST_COMPUTE_HEAP_SIZE_GB:3}
      entrypoint: ${IEXEC_TEE_WORKER_POST_COMPUTE_ENTRYPOINT:/bin/bash /apploader.sh}

  gramine:
    sps:
      login: ${IEXEC_GRAMINE_SPS_WEB_LOGIN:admin}
      password: ${IEXEC_GRAMINE_SPS_WEB_PASSWORD:admin}
