server:
  port: ${IEXEC_SMS_PORT:15443}
  http:
    enabled: ${IEXEC_SMS_HTTP_ENABLED:true}
    port: ${IEXEC_SMS_HTTP_PORT:15000}
  ssl:
    key-store: ${IEXEC_SMS_SSL_KEYSTORE:./src/main/resources/ssl-keystore-dev.p12} #iexec-core dev certificate for dev
    key-store-password: ${IEXEC_SMS_SSL_KEYSTORE_PASSWORD:whatever}
    key-store-type: ${IEXEC_SMS_SSL_KEYSTORE_TYPE:PKCS12}
    key-alias: ${IEXEC_SMS_SSL_KEYSTORE_ALIAS:iexec-core}
    client-auth: need

# Not sure it's a good idea but here is a link for an embedded mongodb
# https://www.baeldung.com/spring-boot-embedded-mongodb
#spring:
#  data:
#    mongodb:
#      database: iexec-sms
#      host: ${IEXEC_SMS_MONGO_HOST:localhost}
#      port: ${IEXEC_SMS_MONGO_PORT:37017}
      #ssl-enabled: true

# Embedded H2 inside JVM
spring:
  datasource:
    url: ${IEXEC_SMS_H2_URL:jdbc:h2:file:/tmp/h2/sms-h2} # will get or create /tmp/h2/sms-h2.mv.db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: ${IEXEC_SMS_H2_CONSOLE:true} # http://localhost:15000/h2-console/
      #settings.web-allow-others: true # Get console if Docker run

encryption:
  # Will get previous key or else create one on this path
  # this file shouldn't be clearly readable outside the enclave (but encrypted content could be copied outside)
  aesKeyPath: ${IEXEC_SMS_STORAGE_ENCRYPTION_AES_KEY_PATH:./src/main/resources/iexec-sms-aes.key} # /scone/iexec-sms-aes.key

blockchain:
  id: ${IEXEC_CHAIN_ID:17}
  nodeAddress: ${IEXEC_SMS_BLOCKCHAIN_NODE_ADDRESS:http://localhost:8545}
  hubAddress: ${IEXEC_HUB_ADDRESS:0x60E25C038D70A15364DAc11A042DB1dD7A2cccBC}
  gasPriceMultiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.0} # txs will be send with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
  gasPriceCap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap
  isSidechain: ${IEXEC_IS_SIDECHAIN:false}

scone:
  cas:
    host: ${IEXEC_SCONE_CAS_HOST:localhost}
    port: ${IEXEC_SCONE_CAS_PORT:8081}
    palaemon:
      configFile:
        withDataset: ${IEXEC_PALAEMON_CONFIG_FILE_WITH_DATASET:./src/main/resources/palaemonConfTemplateWithDataset.vm}
        withoutDataset: ${IEXEC_PALAEMON_CONFIG_FILE_WITHOUT_DATASET:./src/main/resources/palaemonConfTemplateWithoutDataset.vm}
  mrenclave: # TODO: Read that from requester params
    tee-post-compute: # nexus.iex.ec/tee-worker-post-compute:1.0.1-SNAPSHOT
      "89230dce7f4e5ebfe5c96280f8c118abb40e7fdbcfbdc15ea8ef729dc396bcc9|7537d230ad7d1d4533ab4a02ec6018e2|a5681b7b4c77f284880c95f194c8db17929512cacae021e23cd698fe1100784e"
    #tee-post-compute: # nexus.iex.ec/tee-worker-post-compute:1.0.0
      #"734c1ea7089656d32071d03394761cc64e980257d5f0816c6709ccdc063ee56f|757e5b64ba76c92888f5bf6648f7edfd|a5681b7b4c77f284880c95f194c8db17929512cacae021e23cd698fe1100784e"
