version: '3.4'

networks:
  iexec-net:
    external: true

services:

  iexec-sms:
    image: jeremyjames/iexec-sms:dev
    container_name: iexec-sms
    environment:
      - SCONE_CAS_ADDR=iexec-cas:18765
      - SCONE_LAS_ADDR=iexec-las:18766
      - SCONE_CONFIG_ID=s1/iexec-sms
      - SCONE_HEAP=3G
      - SCONE_LOG=7
      - SCONE_VERSION=1
    ports:
      - 15000:15000
      - 15443:15443
    networks:
      - iexec-net
    devices:
      - /dev/isgx
    volumes:  # share volumes for external backup (such as /scone)
      - /tmp/scone:/scone #remind to mkdir /tmp/scone before compose up
  #    entrypoint: /bin/sh # required when manual enclave java boot
  #    stdin_open: true
  #    tty: true

  iexec-cas:
    image: iexechub/iexec-cas:0.0.3
    container_name: iexec-cas
    ports:
      - 18765:18765
      - 18767:8081
    networks:
      - iexec-net
    devices:
      - /dev/isgx

  iexec-las:
    image: iexechub/iexec-las:0.0.2
    container_name: iexec-las
    ports:
      - 18766:18766
    networks:
      - iexec-net
    devices:
      - /dev/isgx

  chain:
    image: jeremyjames/poco-chain:lv3.0.35-2
    container_name: chain
    ports:
      - 8545:8545
    networks:
      - iexec-net
