# Run database in-mem
spring:
  datasource:
    url: jdbc:h2:mem:db

encryption:
  # Will get previous key or else create one on this path
  # this file shouldn't be clearly readable outside the enclave (but encrypted content could be copied outside)
  aesKeyPath: src/test/resources/iexec-sms-aes.key

tee:
  worker:
    pre-compute:
      image: some
      fingerprint: some
      heap-size-gb: 3
      entrypoint: some
    post-compute:
      image: some
      fingerprint: some
      heap-size-gb: 3
      entrypoint: some
  scone:
    las-image: some
